"""
Example: TFIM real-time evolution with ED and NQS-TDVP
======================================================

This example evolves a small transverse-field Ising model on a 2x2 square
lattice from a uniform product state that is exactly representable by a zeroed
RBM. It compares:

    - the Loschmidt amplitude C(t) = <psi(0)|psi(t)>,
    - the corresponding FFT-based spectral estimate,

between exact diagonalization and NQS time evolution generated by TDVP.

The figures are saved under ``Python/tmp/nqs``. The TDVP evolution uses an
explicit fourth-order integrator, internal substeps smaller than the output
time grid, and enough Monte Carlo statistics for the Loschmidt benchmark to
track ED rather than just demonstrate API usage.
"""

import os
import sys

import numpy as np

current_dir = os.getcwd()
if os.path.isdir(os.path.join(current_dir, "Python")):
    sys.path.append(os.path.join(current_dir, "Python"))

import jax
import jax.numpy as jnp

from QES.Algebra.Properties.time_evo import time_evo_block
from QES.Algebra.Model.Interacting.Spin.transverse_ising import TransverseFieldIsing
from QES.Algebra.hilbert import HilbertSpace
from QES.NQS.nqs import NQS
from QES.general_python.common.plot import Plotter, configure_style
from QES.general_python.lattices import SquareLattice
from QES.general_python.ml.net_impl.networks.net_rbm import RBM


def _output_dir():
    """
    Save plots under the Python-library local tmp directory.
    """

    repo_root = current_dir if os.path.isdir(os.path.join(current_dir, "Python")) else os.path.abspath(
        os.path.join(os.path.dirname(__file__), "..", "..")
    )
    outdir = os.path.join(repo_root, "Python", "tmp", "nqs")
    os.makedirs(outdir, exist_ok=True)
    return outdir


def _fft_correlator(times, correlator, *, eta=0.2, window="hann"):
    """
    Convert a real-time correlator into a positive-frequency spectral estimate.

    The same broadening and windowing philosophy is used as in the NQS spectral
    helper so the ED and TDVP line shapes can be compared on the same footing.
    """

    times = np.asarray(times, dtype=float)
    corr = np.asarray(correlator, dtype=np.complex128)
    dt = float(times[1] - times[0])
    t_rel = times - times[0]
    if eta > 0:
        corr = corr * np.exp(-eta * t_rel)
    if window == "hann":
        corr = corr * np.hanning(corr.size)
    elif window == "hamming":
        corr = corr * np.hamming(corr.size)

    raw_fft = np.fft.fftshift(np.fft.fft(corr) * dt)
    freqs = np.fft.fftshift(2.0 * np.pi * np.fft.fftfreq(corr.size, d=dt))
    mask = freqs >= -1e-12
    return freqs[mask], np.real(raw_fft[mask])


def build_uniform_state(seed: int = 0):
    """
    Build a 2x2 TFIM together with an RBM representing the uniform state.

    Zero network parameters give log psi(s) = const, so the normalized wave
    function is the equal-amplitude superposition over all spin configurations.
    This makes the ED comparison especially clean.
    """

    lattice = SquareLattice(dim=2, lx=2, ly=2, bc="obc")
    hilbert = HilbertSpace(lattice=lattice)
    model = TransverseFieldIsing(
        lattice=lattice,
        hilbert_space=hilbert,
        j=1.0,
        hx=0.7,
        hz=0.0,
        dtype=np.complex128,
    )

    net = RBM(
        input_shape=(hilbert.ns,),
        n_hidden=2 * hilbert.ns,
        seed=seed,
        dtype=jnp.complex128,
        param_dtype=jnp.complex128,
    )
    zero_params = jax.tree_util.tree_map(lambda x: jnp.zeros_like(x), net.get_params())
    net.set_params(zero_params)

    nqs = NQS(
        logansatz=net,
        model=model,
        hilbert=hilbert,
        sampler="vmc",
        batch_size=256,
        backend="jax",
        dtype=np.complex128,
        symmetrize=False,
        verbose=False,
        seed=seed,
        s_numsamples=512,
        s_numchains=16,
        s_therm_steps=8,
        s_sweep_steps=1,
    )
    nqs.set_params(zero_params)
    return model, nqs


def _save_time_domain_plot(times, exact_corr, nqs_corr, outdir):
    fig, axes = Plotter.get_subplots(
        nrows=2,
        ncols=1,
        sizex=6.0,
        sizey=5.2,
        share_x=True,
    )

    Plotter.plot(axes[0], times, np.real(exact_corr), color="black", label="ED", linewidth=1.6)
    Plotter.plot(axes[0], times, np.real(nqs_corr), color="C0", label="NQS-TDVP", linewidth=1.4)
    Plotter.set_ax_params(
        axes[0],
        ylabel=r"$\mathrm{Re}\,C(t)$",
        title="TFIM 2x2 Loschmidt amplitude",
    )
    Plotter.set_tickparams(axes[0], labelsize=9)
    Plotter.grid(axes[0], alpha=0.25)
    Plotter.set_legend(axes[0], loc="best")

    Plotter.plot(axes[1], times, np.imag(exact_corr), color="black", label="ED", linewidth=1.6)
    Plotter.plot(axes[1], times, np.imag(nqs_corr), color="C1", label="NQS-TDVP", linewidth=1.4)
    Plotter.set_ax_params(
        axes[1],
        xlabel=r"$t$",
        ylabel=r"$\mathrm{Im}\,C(t)$",
    )
    Plotter.set_tickparams(axes[1], labelsize=9)
    Plotter.grid(axes[1], alpha=0.25)

    Plotter.save_fig(outdir, "tfim_time_evolution_compare.png", format="png", dpi=220, adjust=False, fig=fig)
    return os.path.join(outdir, "tfim_time_evolution_compare.png")


def _save_frequency_plot(freqs_exact, spec_exact, freqs_nqs, spec_nqs, outdir):
    fig, ax = Plotter.get_subplots(
        nrows=1,
        ncols=1,
        sizex=5.6,
        sizey=3.4,
        single_if_1=True,
    )
    Plotter.plot(ax, freqs_exact, spec_exact, color="black", label="ED", linewidth=1.6)
    Plotter.plot(ax, freqs_nqs, spec_nqs, color="C3", label="NQS-TDVP", linewidth=1.4)
    Plotter.set_ax_params(
        ax,
        xlabel=r"$\omega$",
        ylabel=r"$A(\omega)$",
        title="FFT estimate from Loschmidt amplitude",
    )
    Plotter.set_tickparams(ax, labelsize=9)
    Plotter.grid(ax, alpha=0.25)
    Plotter.set_legend(ax, loc="best")
    Plotter.save_fig(outdir, "tfim_time_evolution_spectrum_compare.png", format="png", dpi=220, adjust=False, fig=fig)
    return os.path.join(outdir, "tfim_time_evolution_spectrum_compare.png")


def main():
    configure_style("publication", font_size=10, dpi=140)

    outdir = _output_dir()
    times = np.linspace(0.0, 0.20, 9)
    eta = 0.3

    model, nqs = build_uniform_state(seed=0)
    trajectory = nqs.time_evolve(
        times,
        num_samples=512,
        num_chains=16,
        n_batch=256,
        diag_shift=1e-3,
        sr_maxiter=256,
        ode_solver="RK4",
        max_dt=0.005,
        restore=True,
    )
    spectral_nqs = nqs.spectral_function(times, trajectory=trajectory, eta=eta)

    model.diagonalize()
    eig_vec = np.asarray(model._eig_vec)
    eig_val = np.asarray(model._eig_val)
    psi0 = np.ones(eig_vec.shape[0], dtype=np.complex128)
    psi0 /= np.linalg.norm(psi0)
    overlaps = eig_vec.conj().T @ psi0
    psi_t = time_evo_block(eig_vec, eig_val, overlaps, times)
    exact_corr = np.einsum("i,it->t", np.conj(psi0), psi_t)
    exact_freqs, exact_spec = _fft_correlator(times, exact_corr, eta=eta, window="hann")

    time_plot = _save_time_domain_plot(times, exact_corr, spectral_nqs.correlator, outdir)
    freq_plot = _save_frequency_plot(
        exact_freqs,
        exact_spec,
        spectral_nqs.frequencies,
        spectral_nqs.spectrum,
        outdir,
    )

    print("=" * 72)
    print("TFIM 2x2 square lattice: ED vs NQS-TDVP time evolution")
    print("=" * 72)
    print(f"Times: {times}")
    print(f"Max |C_nqs(t) - C_exact(t)|: {np.max(np.abs(spectral_nqs.correlator - exact_corr)):.6e}")
    print(f"Saved time-domain plot: {time_plot}")
    print(f"Saved spectral plot:    {freq_plot}")
    print()
    print("t        exact(Re)     nqs(Re)       exact(Im)     nqs(Im)")
    for t, c_ex, c_nqs in zip(times, exact_corr, spectral_nqs.correlator):
        print(
            f"{t:5.2f}    {np.real(c_ex): .6f}   {np.real(c_nqs): .6f}"
            f"   {np.imag(c_ex): .6f}   {np.imag(c_nqs): .6f}"
        )


if __name__ == "__main__":
    main()
